
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.text.StyleConstants;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author My Computer
 */
public class Chomp extends javax.swing.JFrame {

    public JButton button;
    public JButton[][] buttons = new JButton[4][8];
    Color color = new Color(96, 54, 2);
    String winner;

    /*buttons = {{x0y0,x1y0,x2y0,x3y0,x4y0,x5y0,x6y0,x7y0},
                                   {x0y1,x1y1,x2y1,x3y1,x4y1,x5y1,x6y1,x7y1},
                                   {x0y2,x1y2,x2y2,x3y2,x4y2,x5y2,x6y2,x7y2},
                                   {x0y3,x1y3,x2y3,x3y3,x4y3,x5y3,x6y3,x7y3}
        };*/
    /**
     * Creates new form Chomp
     */
    public Chomp() {
        getContentPane().setBackground(Color.yellow);
        initComponents();
        jPanel1.setBackground(Color.yellow);
        jTextField1.setText(" Player 1 goes ");
        jTextField1.setFont(new Font("Arial", Font.ITALIC, 15));
        JButton xbutton = new JButton("X");
        xbutton.setFont(new Font("Arial", Font.PLAIN, 40));

        for (int i = 0; i < 4; i++) {
            for (int j = 0; j < 8; j++) {
                if (i == 3 && j == 0) {
                    jPanel1.add(xbutton);
                } else {
                    jPanel1.add(new JButton(""));
                }

            }

        }
        for (Component component : jPanel1.getComponents()) {
            component.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mousePressed(java.awt.event.MouseEvent evt) {
                    MousePressed(evt);
                }

                private void MousePressed(MouseEvent evt) {
                    boolean flag = play((JButton) evt.getComponent());
                    if (flag) {
                        if (jTextField1.getText().equals(" Player 1 goes ")) {
                            jTextField1.setText(" Player 2 goes ");
                        } else {
                            jTextField1.setText(" Player 1 goes ");
                        }
                    }

                }
            });
            component.setBackground(color);
        }

        int k = 0;

        for (int i = 0; i < 4; i++) {
            for (int j = 0; j < 8; j++) {
                buttons[i][j] = (JButton) jPanel1.getComponent(k);
                k++;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTryAgain = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        btnTryAgain.setBackground(new java.awt.Color(204, 0, 0));
        btnTryAgain.setText("Try Again");
        btnTryAgain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTryAgainActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 0));
        jPanel1.setLayout(new java.awt.GridLayout(4, 8));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(387, 387, 387)
                        .addComponent(btnTryAgain, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnTryAgain, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTryAgainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTryAgainActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(" Player 1 goes ");
        restart();
    }//GEN-LAST:event_btnTryAgainActionPerformed

    boolean play(JButton btn) {

        int x = 0, y = 0;
        for (int i = 0; i < 4; i++) {
            for (int j = 0; j < 8; j++) {
                button = buttons[i][j];
                if (btn.getBackground().equals(Color.white)) {
                    //System.out.println("oyuncu değişmesin");
                    x = -1;
                    y = 9;
                    return false;

                }
                else if (btn == buttons[3][0]) {
                    return false;
                }
                else if (button.equals(btn)) {
                    x = i;
                    y = j;
                    System.out.println(button.getText() + " : " + i + " " + j);
                }
            }
        }

        

        if (btn == buttons[3][1] && buttons[2][0].getBackground().equals(Color.white)) {

            System.out.println("Oyun bitti");

            if (jTextField1.getText().equals(" Player 1 goes ")) {

                winner = "PLAYER 1 WINS !";

            } else {
                winner = "PLAYER 2 WINS !";
            }

            JOptionPane.showMessageDialog(null,
                    winner,
                    "CONGRATULATIONS",
                    JOptionPane.INFORMATION_MESSAGE);

        } else if (btn == buttons[2][0] && buttons[3][1].getBackground().equals(Color.white)) {

            System.out.println("oyun bitti");

            if (jTextField1.getText().equals(" Player 1 goes ")) {

                winner = "PLAYER 1 WINS !";

            } else {
                winner = "PLAYER 2 WINS !";
            }

            JOptionPane.showMessageDialog(null,
                    winner,
                    "CONGRATULATIONS",
                    JOptionPane.INFORMATION_MESSAGE);

        }

        for (int i = x; i >= 0; i--) {
            for (int j = y; j < 8; j++) {
                //System.out.println(i + " " + j);
                buttons[i][j].setBackground(Color.white);
                jPanel1.add(buttons[i][j], (x * 8 + y));
            }
        }

        return true;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Chomp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Chomp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Chomp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Chomp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Chomp().setVisible(true);

            }
        });

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTryAgain;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    private void restart() {

        for (Component component : jPanel1.getComponents()) {

            component.setBackground(color);
        }
    }
}
